name: Deploy to GitHub Pages

on:
  push:
    branches: gh-pages
  workflow_dispatch:

jobs:
  deploy:
    uses: importantimport/.github/.github/workflows/pnpm-gh-pages.yml@main
    permissions:
      contents: write
    with:
      publish_dir: build
